# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MHS Links
description: A collection of links (and more) for Melbourne High School.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhslinks.github.io" # the base hostname & protocol for your site
real_name: MHS
real_home: "https://mhs.vic.edu.au"
source_url: "https://github.com/mhslinks/mhslinks.github.io"
exclude: ['README.md', 'CONTRIBUTING.md', 'Gemfile.lock', 'Gemfile']
